config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index' , as: 'amrut'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
	get 'articles/app'
  resources :articles do
  	resources :comments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: {message: "Title field should bbe given"}, length: { minimum: 5 } 
	validates :text, presence: true
	puts ActiveModel::Validations::Callbacks.class	
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

   # validates_associated :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  def app
  	# render :app
  	render plain: "hello"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	def index
		@article = Article.all
		
		respond_to do |format|
			format.html
			format.json {render json: @article}
		end
	end
	def app
		redirect_to "https://www.google.com"
	end
	def show
		@article = Article.find(params[:id])
		# render json: @article
		respond_to do |format|
			format.html
			format.json {render json: @article}
		end
	end

	def new
		@article = Article.new
	end
	def edit
		@article = Article.find(params[:id])
	end

	def create
		 @article = Article.new(article_params)
		  if @article.save
		  		flash[:notice] = " Article is successfully created."
		  		respond_to do |format|
					format.html
					format.json {render json: @article}
				end
		  else
		    	# render nothing: true, status: :bad_request
		    	render json: @article.errors.full_messages, status: :bad_request
		  end
	end
	def update
		  @article = Article.find(params[:id])
		 
		  if @article.update(article_params)
		    	respond_to do |format|
					format.html
					format.json {render json: @article}
				end
		  else
		    	render nothing: true, status: :bad_request
		  end
	end
	def destroy
		 @article = Article.find(params[:id])
		 if @article.destroy
		 	respond_to do |format|
				format.html
				format.json {render json: @article}
			end
		 else
		  render nothing: true, status: :bad_request
		 end
	end

	private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
	    @article = Article.find(params[:article_id])
      puts @article.inspect                         #for security purposes only 
	    @comment = @article.comments.create(comment_params)
	    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
     	 params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def full_title(page_title)
		base title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
		base title
		else
		"#{base title} | #{page title}"
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_footer.html.erb
<p>
	Footer partial rendering.
</p>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% content_for :page_title do %>
    Awesome page
<% end %>
<%= content_for?(:page_title) ? yield(:page_title) : "default page title" %>
<title><%= yield(:title) %></title>
<h1>Listing articles</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @article.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= render "footer" %>
<div id='result'>
  
</div>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path , format: :json%>
<%= render partial: "footer",layout: "layouts/app" %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<%= flash[:notice] %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<%= @article.comments.inspect %><br>
<%= @article.comments.build.inspect %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_app.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		hi
	</title>
</head>
<body>
hi application contoller
</body>

<p>
	<%= render "articles/footer" %>
</p>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<h1>Hello Rails</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<body>
</body>

<div id="article-form">
	
</div>